site_name: pygris
site_url: https://walker-data.com/pygris
repo_url: https://github.com/walkerke/pygris

theme: 
  name: material
  palette: 
    primary: black

plugins:
  - mkdocs-jupyter:
      execute: True
      include_source: True
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
