site_name: pygris
site_url: https://walker-data.com/pygris
repo_url: https://github.com/walkerke/pygris

theme: 
  name: material
  palette: 
    primary: black
  icon: 
    repo: fontawesome/brands/github
  logo: img/tiger_map_small.png
  favicon: img/tiger_map_small.png

plugins:
  - mkdocs-jupyter:
      execute: True
      include_source: True
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
